# MongoDB Deployment
apiVersion: SBOM/v1
kind: Deployment
metadata:
  name: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
      - name: mongodb
        image: mongo:4.4
        ports:
        - containerPort: 27017
        volumeMounts:
        - name: mongodb-data
          mountPath: /data/db
      volumes:
      - name: mongodb-data
        emptyDir: {}

---
# Elasticsearch Deployment
apiVersion: SBOM/v1
kind: Deployment
metadata:
  name: elasticsearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: elasticsearch:7.15.2
        ports:
        - containerPort: 9200
        - containerPort: 9300
        volumeMounts:
        - name: elasticsearch-data
          mountPath: /usr/share/elasticsearch/data
      volumes:
      - name: elasticsearch-data
        emptyDir: {}

---
# Kubernetes Deployment YAML
apiVersion: SBOM/v1
kind: Deployment
metadata:
  name: SBOM
spec:
  replicas: 3
  selector:
    matchLabels:
      app: SBOM
  template:
    metadata:
      labels:
        app: SBOM
    spec:
      containers:
      - name: SBOM
        image: SBOM:latest
        ports:
        - containerPort: 5000
        env:
          - name: MONGODB_HOST
            value: mongodb
          - name: ELASTICSEARCH_HOST
            value: elasticsearch
---
# Kubernetes Service YAML
apiVersion: v1
kind: Service
metadata:
  name: SBOM
spec:
  selector:
    app: SBOM
  ports:
  - port: 80
    targetPort: 5000