version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - sbom_network
    

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sbom_network

  selenium:
    image: selenium/standalone-chromium:nightly
    #image: euler-selenium:latest
    shm_size: 2gb
    container_name: selenium
    ports:
     - "4444:4444"
     - "7900:7900"
     - "5900:5900"
    ulimits:
      nofile:
        soft: 32768
        hard: 32768
    environment:
     - SE_START_NO_VNC=false
     - SE_START_VNC=false
    networks:
     - sbom_network

  sbom:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sbom
    depends_on:
      - elasticsearch
      - mongodb
      - selenium
    ports:
      - "5000:5000"
    networks:
      - sbom_network

networks:
  sbom_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

volumes:
  es_data:
  mongodb_data:
