version: '3.8'

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.12.1
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - es_data:/usr/share/elasticsearch/data
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    networks:
      - sbom_network
    

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - sbom_network

  sbom:
    build:
      context: .
      dockerfile: dockerfile
    container_name: sbom
    depends_on:
      - elasticsearch
      - mongodb
    ports:
      - "5000:5000"
    networks:
      - sbom_network

networks:
  sbom_network:
    driver: bridge

volumes:
  es_data:
  mongodb_data:
