#!/bin/bash

# Function to check if a Docker container is running
container_exists() {
    docker ps -a --format '{{.Names}}' | grep -q "$1"
}

# Check if MongoDB and Elasticsearch containers are already running
if ! container_exists "mongodb"; then
    echo "MongoDB container is not running. Starting MongoDB container using Docker Compose..."
    docker-compose -f docker-compose.yaml up -d mongodb
fi

if ! container_exists "elasticsearch"; then
    echo "Elasticsearch container is not running. Starting Elasticsearch container using Docker Compose..."
    docker-compose -f docker-compose.yaml up -d elasticsearch
fi

# Start the SBOM container using the Dockerfile
docker build -t sbom .
echo "Building SBOM container..."
docker run -d --name sbom -p 5000:5000 --link mongodb --link elasticsearch sbom
echo "all container already started..."